### ISSUE TITLE
fastscroller bubble

### ISSUE THREAD

**Issue by addelll** [FutureMind/recycler-fast-scroll#10]
fastscroller bubble there is any way to chage size?

**Comment by micHar** [comment]
There are plans to make the whole widget styleable, but as for now, you would have to fork it and change the bubble in the lib.
https://github.com/FutureMind/recycler-fast-scroll/issues/2

**Comment by micHar** [comment]
@addelll You can now provide your own bubble layout with `ScrollerViewProvider`. Since you only want to change the size of the bubble, I suggest extending `DefaultScrollerViewProvider`.

**Comment by addelll** [comment]
Thank you , but i forked the project i changed.
