### ISSUE TITLE
Attribute Issue and Bubble offset

### ISSUE THREAD

**Issue by csimmonsbluebook** [FutureMind/recycler-fast-scroll#14]
When trying to set the bubble color and handle color I received errors saying that those attributes are not in my package. Any idea why this is happening? I added the library through gradle so it should be there.

Also, is there a way to set the offset of the bubble from the handle? It is currently quite close to the handle and your finger covers the bubble.

**Comment by MGaetan89** [comment]
I am having the same issue...

**Comment by MGaetan89** [comment]
I had a look at the resources included in the library, and the styleable attributes are not there. So maybe they were added after the latest release?
Until there is an official solution/fix, I directly override the resource I need (drawable, dimension, ...).

**Comment by micHar** [comment]
It wasn't quite ready to be released. I fixed several things today and released it to the jCenter. You can use 0.1.5 in gradle now.

As for the second issue with the offset - it will be added along with a few other styleable attributes. I will close this issue now, you can subscribe to [this issue](https://github.com/FutureMind/recycler-fast-scroll/issues/2).

**Comment by csimmonsbluebook** [comment]
@micHar Great, thanks!

**Comment by MGaetan89** [comment]
Thanks for the update @micHar
