### ISSUE TITLE
Scroll bar not visible

### ISSUE THREAD

**Issue by ndrdmarshmallow** [FutureMind/recycler-fast-scroll#23]
Am using this with gradle in my project. i have attached the fastscroller as mentioned in example but am not seeing the scroll bar in output.

**Comment by micHar** [comment]
Do you have any items in your `RecyclerView.Adapter`? There is a mechanism which hides the fastscroller if there are not enough items on the list (i.e. the list is shorter than the available screen estate).

**Comment by micHar** [comment]
Did you fix it or do you still need some help?

**Comment by Moha6584** [comment]
am having the the same problem and i have more than 300 items

**Comment by micHar** [comment]
You have to post some details, your code etc, otherwise there is no possibility I can help you fix it.

**Comment by Moha6584** [comment]
https://gist.github.com/Moha6584/0cce5d1b0ff67be70976755d3b23da47 . that's my mainactivity and contantmain

**Comment by micHar** [comment]
Please, take a look at [minimal working example](https://github.com/FutureMind/recycler-fast-scroll/blob/master/README.md#minimal-working-example). 

```java
        recyclerView = (RecyclerView) findViewById(R.id.recyclerview);
        fastScroller = (FastScroller) findViewById(R.id.fastscroll);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        recyclerView.setAdapter(adapter);

        //has to be called AFTER RecyclerView.setAdapter()
        fastScroller.setRecyclerView(recyclerView);
```

You are calling setAdapter() after setRecyclerView which doesn't work. Try fixing and and tell me if it works.

**Comment by Moha6584** [comment]
i did and nothing changed its still the same, the recycleeview scroll bar is visible thought

**Comment by micHar** [comment]
Can you post a screenshot?

**Comment by Moha6584** [comment]
![whatsapp image 2016-09-02 at 10 05 20](https://cloud.githubusercontent.com/assets/21177710/18195569/e9501572-70f4-11e6-89ad-af6f4a80fe20.jpeg)

**Comment by micHar** [comment]
And your adapter? Does it implements `SectionTitleProvider` and properly overrides `getSectionTitle()`? Can you post it?

**Comment by Moha6584** [comment]
https://gist.github.com/Moha6584/c04011116eff465ac50d099b4fbc557d

**Comment by micHar** [comment]
Well, there's your problem. The adapter provides the bubble letters, your are responsible for adding this. I should probably add a remark on this to the minimal working example section. 

Take a look on `CountriesAdapter` in the example on how it should be implemented.

**Comment by Moha6584** [comment]
sorry but what example? can you add the link?
thank you

**Comment by micHar** [comment]
I modified the Readme to specify how you should prepare your Adapter for FastScroll: https://github.com/FutureMind/recycler-fast-scroll#minimal-working-example.

The example adapter can be seen here: https://github.com/FutureMind/recycler-fast-scroll/blob/master/example/src/main/java/com/futuremind/recyclerviewfastscroll/example/adapters/CountriesAdapter.java

**Comment by Moha6584** [comment]
how can i customize my adapter without loosing my filterable method and impliment the SectionTitleProvider

**Comment by micHar** [comment]
Well, just:

`public class WordAdapter extends RecyclerView.Adapter<MyViewHolder> implements Filterable, SectionTitleProvider {`

Sorry, but this is outside of the scope of support I can provide here. This is a general programming question, if you have those, you should probably head to stackoverflow.
