### ISSUE TITLE
Could you add auto hiding when RecyclerView is not touched

### ISSUE THREAD

**Issue by raymanzhang** [FutureMind/recycler-fast-scroll#26]
The fast scroll bar is always visible, is there any way to hide it automatically when the user does not touch the RecyclerView for a while?

**Comment by micHar** [comment]
Yes, there is. It's not directly exposed (maybe it will be), but you can easily implement it yourself. See the example code and the [`CustomViewFragment`](https://github.com/FutureMind/recycler-fast-scroll/blob/master/example/src/main/java/com/futuremind/recyclerviewfastscroll/example/fragments/CustomViewFragment.java) which does exactly that.

Of course the `CustomScrollerViewProvider` uses lots of code to showcase various features, but you can just inherit from `DefaultScrollerViewProvider` and only extend `provideHandleBehavior()`.

**Comment by raymanzhang** [comment]
Great works, Thank you! And IMHO this feature should be part of the library.
