### ISSUE TITLE
android:allowBackup=true forces me to use tools:replace

### ISSUE THREAD

**Issue by awenger** [FutureMind/recycler-fast-scroll#27]
https://github.com/FutureMind/recycler-fast-scroll/blob/6b216b47ca4c99167dd59b8e5e1b4c1555bc02b2/fastscroll/src/main/AndroidManifest.xml#L4

see:
https://github.com/chrisbanes/PhotoView/issues/199
https://github.com/OfficeDev/msa-auth-for-android/issues/21

**Comment by micHar** [comment]
Thank you for noticing this. I fixed it in 0.2.4 which should be already available in jcenter.

**Comment by awenger** [comment]
that was quick. Thank you!
