### ISSUE TITLE
RecyclerView Not Wrapping content for horizontal scroll

### ISSUE THREAD

**Issue by rizasif** [FutureMind/recycler-fast-scroll#37]
I am using trying use a horizontal list of image views. The list displays fine but the fastscroll and recyclerView has some offset in between that I don't understand why.

    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:layout_below="@+id/upper_widget_bar"
        android:background="@color/colorPrimaryDark">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recyclerview"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal"/>

        <com.futuremind.recyclerviewfastscroll.FastScroller
            android:id="@+id/fastscroll"
            android:orientation="horizontal"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>

    </LinearLayout>

**Comment by micHar** [comment]
It's because you are using LinearLayout which makes one view display below another (in y-axis). If you used FrameLayout the FastScroller would appear above the RecyclerView in z-axis. Try this

```
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_below="@+id/upper_widget_bar"
    android:background="@color/colorPrimaryDark">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recyclerview"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal"/>

    <com.futuremind.recyclerviewfastscroll.FastScroller
        android:id="@+id/fastscroll"
        android:orientation="horizontal"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>

</FrameLayout>
```

**Comment by micHar** [comment]
Just to be clear. Remember that the FastScroll is not only the thin handle, it's also the bubble, which is why it takes more place than it initially appears.

**Comment by rizasif** [comment]
okay but can't we make it invisible somehow, because in my case it is taking a lot of space.

![image](https://cloud.githubusercontent.com/assets/8410351/20303768/d18db5ea-ab4e-11e6-999f-e77166b8e279.png)

**Comment by micHar** [comment]
If you used `FrameLayout` and it's still taking too much place for you, you can always provide your own implementation of bubble. Follow the sample for custom view - `provideBubbleView` [here](https://github.com/FutureMind/recycler-fast-scroll/blob/master/example/src/main/java/com/futuremind/recyclerviewfastscroll/example/customview/CustomScrollerViewProvider.java).
