### ISSUE TITLE
Scrollbar not visible at first

### ISSUE THREAD

**Issue by MinaHany** [FutureMind/recycler-fast-scroll#38]
Not sure if this is a bug of if I'm missing something so thought I'd ask.

I have a RecyclerView that consists of varying heights TextViews (and some of the TextViews are larger than the full screen height).

When my view is first loaded, I do not see the scrollbar at all. In this case the first TextView is larger than the full screen height. As soon as I scroll down to the first line in the second TextView, the scrollbar shows up.

After that the scrollbar sticks and works fine even when scrolling back up to the top.

Any idea what might be happening here?

**Comment by micHar** [comment]
This is essentially the same issue as #39, so I will close it as duplicate and we will continue there.
