### ISSUE TITLE
How to Set fastscroll on viewpager

### ISSUE THREAD

**Issue by AhmadullahSaikat** [FutureMind/recycler-fast-scroll#40]
This method works
fastScrollerHorizontal.setRecyclerView(recyclerViewHorizontal);

but there is no method like this
fastScrollerHorizontal.setViewPager(viewPager);

is there any way to use FAST SCROLLER on viewpager?

**Comment by micHar** [comment]
No, it only works with `RecyclerView`. The `RecyclerView` and `ViewPager` are completely different components with different APIs, so it might be hard to make it work for both, but if you handle to do it, a PR would be welcome.
