### ISSUE TITLE
Example does not display bubble 

### ISSUE THREAD

**Issue by emnrd-ito** [FutureMind/recycler-fast-scroll#44]
I have run the example on 3 devices, with Android 7, 5.0.2, and 4.4.4 and the bubble does not display (though the handle does). In Android Studio, I set a break point at `CountriesAdapter.getSectionTitle()` and it never gets there.

**Comment by micHar** [comment]
You grab the handle and it doesn't show? Maybe I have merged something weird...

**Comment by emnrd-ito** [comment]
Oh, my mistake. I was simply scrolling without grabbing the handle. It works when grabbing then handle. My apologies.
