### ISSUE TITLE
How to auto hide the scrollbar?

### ISSUE THREAD

**Issue by cristarra** [FutureMind/recycler-fast-scroll#47]
I successfully use this library, and fast scroll bars appear so perfectly and easily applied. but I want some animation to fastscroll can disappear automatically, this might be a basic question, but I would be very happy if I get a code that is easier to use. This is my code :

```
View rootView = inflater.inflate(R.layout.fragment, container, false);

RecyclerView rv = (RecyclerView) rootView.findViewById(R.id.recycler_view);
        FastScroller fastScroller = (FastScroller) rootView.findViewById(R.id.FutureMind_fastscroll);
        rv.setHasFixedSize(true);
        Adapter adapter = new Adapter(
                result
        );
        rv.setAdapter(adapter);

        LinearLayoutManager llm = new LinearLayoutManager(getActivity());
        rv.setLayoutManager(llm);
        fastScroller.setRecyclerView(rv);

return rootView;
```

is there a quick way to display the scroll bar at the time of the action by the user and hide automatically when a few seconds if user does not scroll. 

Is there a way to modify my code above and resolve the issue? 
Thank you for the help.

**Comment by hendrawd** [comment]
so what did you do? can you share with us?

**Comment by cristarra** [comment]
In the end I no longer use this library anymore.
