### ISSUE TITLE
Please add null check for recyclerview in FastScroller.java

### ISSUE THREAD

**Issue by jihunim** [FutureMind/recycler-fast-scroll#72]
I want to create FastScroller with INVISIBLE, and, I do not want to execute unnecessary setups until I set it VISIBLE.
`        fastScroller = baseView.findViewById(R.id.fastscroll);
        fastScroller.setViewProvider(new LineFastScrollViewProvider());
        fastScroller.setRecyclerView(recyclerView);`

If I do not execute below code, the problem occurs.
`fastScroller.setRecyclerView(recyclerView);`

I want my program looks like this

> 

        if (mediaContext.getRequestParams().isFastScrollEnabled) {
            fastScroller = baseView.findViewById(R.id.fastscroll);
            fastScroller.setViewProvider(new LineFastScrollViewProvider());
            fastScroller.setRecyclerView(recyclerView);
            fastScroller.setVisibility(View.VISIBLE);
        } else {
            fastScroller = baseView.findViewById(R.id.fastscroll);
            fastScroller.setVisibility(View.INVISIBLE);
        }

Solution:
I think your FastScroller:setVisibility doesn't require recyclerview to be not null.
And on other methods, please add null check for the variable 'recyclerview'

**Comment by Bringoff** [comment]
Just move lines
```
fastScroller = baseView.findViewById(R.id.fastscroll);
fastScroller.setViewProvider(new LineFastScrollViewProvider());
fastScroller.setRecyclerView(recyclerView);
```
out of `if` statement. This is not the library issue.

**Comment by jihunim** [comment]
@Bringoff Thank you very much
